apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: LoadBalancer 
  ports:
    - name: postgres-service
      protocol: TCP
      port: 5432
  selector:
    app: postgres-service
    
    ---
