---
apiVersion: v1
kind: Secret
metadata:
  name: db-credenciais
type: Opaque
data:
  user: dTA0cWQ5YW5pN2U3bTFjdg==
  password: eTA5VGxxdHpPTlNoc3ptYVZ0Q0s=
  root-password: TSNARXN3UFB2QUBp
  database: dXN1YXJpb3M=
---
apiVersion: v1
kind: PersistentVolumeClaim        
metadata:                          
  name: mysql-pv-claim
  labels:
    app: polling-app
spec:                             
  accessModes:
    - ReadWriteOnce               
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1                    
kind: Service                    
metadata:
  name: mysql        
  labels:                         
    app: mysql
spec:
  type: ExternalName
  externalName: mysql-externo-brunoferreirag.cloud.okteto.net
  ports:
    - port: 3306
  selector:                       
    app: mysql
---
apiVersion: apps/v1
kind: Deployment                  
metadata:
  name: mysql          
  labels:                           
    app: mysql
spec:
  selector:
    matchLabels:                   
      app: mysql
  strategy:
    type: Recreate
  template:                         
    metadata:
      labels:                      
        app: mysql
    spec:                           
      containers:
      - image: mysql:5.6            
        name: mysql
        env:                        
        - name: MYSQL_ROOT_PASSWORD 
          valueFrom:                
            secretKeyRef:
              name: db-credenciais
              key: root-password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: db-credenciais
              key: database
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db-credenciais
              key: user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credenciais
              key: password
        ports:
        - containerPort: 3306        # The port that the container exposes       
          name: mysql
        resources:
          requests:
            memory: "512Mi"
            cpu: "256m"
          limits:
            memory: "1024Mi"
            cpu: "512m"
        volumeMounts:
        - name: mysql-persistent-storage  # This name should match the name specified in `volumes.name`
          mountPath: /var/lib/mysql
      volumes:                       # A PersistentVolume is mounted as a volume to the Pod  
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
